---
# tasks file for aap_install
- name: "Install postgresl 12"
  block:
  # Variable configuration.
  - include_tasks: variables.yml
  
  # Setup/install tasks.
  - include_tasks: setup-RedHat.yml
    when: ansible_os_family == 'RedHat'
  
  - include_tasks: initialize.yml
  - include_tasks: configure.yml
  
  # Configure PostgreSQL.
  - import_tasks: users.yml
  - import_tasks: databases.yml
  - import_tasks: users_props.yml
  when: "'pgsql' in inventory_hostname"
  tags:
    - pgsql
